# Generated by Django 3.0.4 on 2020-03-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='bluetooth_version',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='nfc',
            field=models.BooleanField(verbose_name='NFC'),
        ),
    ]
