# Generated by Django 3.0.4 on 2020-04-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0002_auto_20200321_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osversion',
            name='os',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='back_camera_video',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='chipset',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='color',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='display_resolution_height',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='display_resolution_width',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='display_technology',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='front_dual_camera',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='height',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='width',
        ),
        migrations.RemoveField(
            model_name='phoneimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='phone',
            name='quick_battery_charging',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Chipset',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='OSVersion',
        ),
        migrations.DeleteModel(
            name='QuickCharge',
        ),
    ]
