# Generated by Django 3.0.4 on 2020-04-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0003_auto_20200408_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='fingerprint',
            field=models.CharField(choices=[('no', 'no'), ('front-mounted', 'front-mounted'), ('rear-mounted', 'rear-mounted'), ('side-mounted', 'side-mounted'), ('under display', 'under display')], max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sim_size',
            field=models.CharField(choices=[('miniSIM', 'miniSIM'), ('microSIM', 'microSIM'), ('NanoSIM', 'nanoSIM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='usb_type',
            field=models.CharField(choices=[('other', 'other'), ('microUSB', 'microUSB'), ('type C', 'type C'), ('lightning', 'lightning')], max_length=20),
        ),
    ]
