# Generated by Django 3.0.4 on 2020-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0005_phone_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='operating_system',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows Phone', 'Windows Phone'), ('other', 'other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
    ]
