# Generated by Django 3.0.4 on 2020-04-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0010_auto_20200415_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='number_of_ratings',
        ),
    ]
