# Generated by Django 3.0.4 on 2020-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
