# Generated by Django 3.0.4 on 2020-04-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0014_auto_20200417_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='main_photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_images',
        ),
        migrations.DeleteModel(
            name='PhoneImage',
        ),
    ]
