# Generated by Django 3.0.4 on 2020-04-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonemodelapi', '0015_auto_20200421_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('author', 'phone')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('author', 'phone')},
        ),
    ]
